---
deployment:
  tasks:
    - export PATH=/opt/cpanel/composer/bin:$PATH
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan migrate --force
    - php artisan storage:link
    - chmod -R 775 storage bootstrap/cache
